# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2018.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion-2018.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rhys/CLionProjects/altair

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rhys/CLionProjects/altair

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2018.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2018.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhys/CLionProjects/altair/CMakeFiles /home/rhys/CLionProjects/altair/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rhys/CLionProjects/altair/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named altairtest

# Build rule for target.
altairtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 altairtest
.PHONY : altairtest

# fast build rule for target.
altairtest/fast:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/build
.PHONY : altairtest/fast

#=============================================================================
# Target rules for targets named altair

# Build rule for target.
altair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 altair
.PHONY : altair

# fast build rule for target.
altair/fast:
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/build
.PHONY : altair/fast

src/cpu.o: src/cpu.c.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.c.o:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/cpu.c.o
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/cpu.c.o
.PHONY : src/cpu.c.o

src/cpu.i: src/cpu.c.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.c.i:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/cpu.c.i
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/cpu.c.i
.PHONY : src/cpu.c.i

src/cpu.s: src/cpu.c.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.c.s:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/cpu.c.s
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/cpu.c.s
.PHONY : src/cpu.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory.o: src/memory.c.o

.PHONY : src/memory.o

# target to build an object file
src/memory.c.o:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/memory.c.o
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/memory.c.o
.PHONY : src/memory.c.o

src/memory.i: src/memory.c.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/memory.c.i
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/src/memory.c.s
	$(MAKE) -f CMakeFiles/altair.dir/build.make CMakeFiles/altair.dir/src/memory.c.s
.PHONY : src/memory.c.s

test/mov_test.o: test/mov_test.c.o

.PHONY : test/mov_test.o

# target to build an object file
test/mov_test.c.o:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/mov_test.c.o
.PHONY : test/mov_test.c.o

test/mov_test.i: test/mov_test.c.i

.PHONY : test/mov_test.i

# target to preprocess a source file
test/mov_test.c.i:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/mov_test.c.i
.PHONY : test/mov_test.c.i

test/mov_test.s: test/mov_test.c.s

.PHONY : test/mov_test.s

# target to generate assembly for a file
test/mov_test.c.s:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/mov_test.c.s
.PHONY : test/mov_test.c.s

test/test.o: test/test.c.o

.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/altairtest.dir/build.make CMakeFiles/altairtest.dir/test/test.c.s
.PHONY : test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... altairtest"
	@echo "... altair"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... test/mov_test.o"
	@echo "... test/mov_test.i"
	@echo "... test/mov_test.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

